import { Drama, Category } from './types';

export const MOCK_DRAMAS: Drama[] = [
  {
    id: '1',
    title: 'The CEO\'s Secret Vow',
    description: 'A billionaire CEO enters a contract marriage to protect his empire, but unexpected love blooms amidst corporate sabotage.',
    thumbnailUrl: 'https://picsum.photos/id/10/300/450',
    coverUrl: 'https://picsum.photos/id/10/1920/1080',
    genre: ['Romance', 'Drama'],
    rating: 4.8,
    year: 2024,
    episodes: 50,
    isVertical: true,
    trending: true,
  },
  {
    id: '2',
    title: 'Shadows of the Palace',
    description: 'In the Joseon era, a lowly maid discovers a conspiracy that threatens the throne and must navigate a web of lies.',
    thumbnailUrl: 'https://picsum.photos/id/15/300/450',
    coverUrl: 'https://picsum.photos/id/15/1920/1080',
    genre: ['Historical', 'Thriller'],
    rating: 4.9,
    year: 2023,
    episodes: 16,
    isVertical: false,
    trending: true,
  },
  {
    id: '3',
    title: 'Cyber Heart',
    description: 'In a futuristic city, an AI researcher falls in love with her creation, sparking a revolution against the tech giants.',
    thumbnailUrl: 'https://picsum.photos/id/20/300/450',
    coverUrl: 'https://picsum.photos/id/20/1920/1080',
    genre: ['Sci-Fi', 'Romance'],
    rating: 4.5,
    year: 2024,
    episodes: 12,
    isVertical: false,
    trending: false,
  },
  {
    id: '4',
    title: 'Reborn for Revenge',
    description: 'Betrayed by her best friend and husband, she wakes up ten years in the past with a chance to rewrite her destiny.',
    thumbnailUrl: 'https://picsum.photos/id/25/300/533', // Vertical ratio
    coverUrl: 'https://picsum.photos/id/25/1920/1080',
    genre: ['Revenge', 'Melodrama'],
    rating: 4.7,
    year: 2024,
    episodes: 80,
    isVertical: true,
    trending: true,
  },
  {
    id: '5',
    title: 'Coffee Prince Returns',
    description: 'The nostalgic aroma of coffee brings together strangers at a mysterious cafe that only opens at midnight.',
    thumbnailUrl: 'https://picsum.photos/id/30/300/450',
    coverUrl: 'https://picsum.photos/id/30/1920/1080',
    genre: ['Slice of Life', 'Comedy', 'Dub Indo'],
    rating: 4.6,
    year: 2023,
    episodes: 20,
    isVertical: false,
    trending: false,
  },
  {
    id: '6',
    title: 'The Last Immortal',
    description: 'A deity falls to earth and loses his memory, only to be found by a struggling street artist.',
    thumbnailUrl: 'https://picsum.photos/id/40/300/533',
    coverUrl: 'https://picsum.photos/id/40/1920/1080',
    genre: ['Fantasy', 'Romance'],
    rating: 4.9,
    year: 2024,
    episodes: 40,
    isVertical: true,
    trending: true,
  },
  {
    id: '7',
    title: 'Urban Legends',
    description: 'A group of students investigates urban myths in their city, discovering some stories are better left untold.',
    thumbnailUrl: 'https://picsum.photos/id/50/300/450',
    coverUrl: 'https://picsum.photos/id/50/1920/1080',
    genre: ['Horror', 'Mystery', 'Dub Indo'],
    rating: 4.4,
    year: 2022,
    episodes: 10,
    isVertical: false,
    trending: false,
  },
  {
    id: '8',
    title: 'Doctor\'s Orders',
    description: 'A genius surgeon with a cold heart meets a warm-hearted pediatrician who changes his perspective on life and medicine.',
    thumbnailUrl: 'https://picsum.photos/id/60/300/450',
    coverUrl: 'https://picsum.photos/id/60/1920/1080',
    genre: ['Medical', 'Romance'],
    rating: 4.7,
    year: 2023,
    episodes: 24,
    isVertical: false,
    trending: true,
  }
];

export const getCategories = (dramas: Drama[] = MOCK_DRAMAS): Category[] => [
  {
    id: 'trending',
    name: 'Trending Now',
    dramas: dramas.filter(d => d.trending),
  },
  {
    id: 'vip',
    name: 'VIP Exclusive',
    dramas: dramas.filter(d => d.isVip),
  },
  {
    id: 'latest',
    name: 'Fresh Arrivals',
    dramas: dramas.filter(d => d.isNew || d.year >= 2025),
  },
  {
    id: 'dubindo',
    name: 'Indonesian Dub (Dub Indo)',
    dramas: dramas.filter(d => d.genre.includes('Dub Indo')),
  },
  {
    id: 'foryou',
    name: 'Recommended For You',
    dramas: dramas.filter(d => !d.trending && !d.genre.includes('Dub Indo') && !d.isVip),
  },
  {
    id: 'vertical',
    name: 'Vertical Shorts',
    dramas: dramas.filter(d => d.isVertical),
  }
];

export const CATEGORIES = getCategories(MOCK_DRAMAS);